In [81]:
# Assignment 1
'''
Create an array of 18 random elements of shape (3, 6) and add the array [0, 0, 2, 4, 5, 3] to each row.
Then reshape it to a (9, 2) array and take its transpose.
Find the locations where all elements are greater than the mean of the array and print it
'''
import numpy as np
# Random array
random_arr = np.random.rand(3, 6)  # Uniform distribution
print("Random Array:\n", random_arr)
#add array
add_arr=np.array([0,0,2,4,5,3])
added_arr=random_arr+add_arr
print("Added Array:\n",added_arr)
#reshape
reshaped_arr=added_arr.reshape(9,2)
print("Reshaped Array:\n",reshaped_arr)
#transpose
transposed_arr=reshaped_arr.T
print("Transposed Array:\n",transposed_arr)
#find locations where all elements are greater than the mean
mean_val=np.mean(transposed_arr)
print("Mean Value:",mean_val)
locations=np.where(transposed_arr>mean_val)
print("Locations where all elements are greater than the mean:\n",locations)

Random Array:
 [[0.71624417 0.02706898 0.73139734 0.76696351 0.00976644 0.30828617]
 [0.23286547 0.50342743 0.95372138 0.5578113  0.09746869 0.62167849]
 [0.86302262 0.15763228 0.99242952 0.08500107 0.09445791 0.63360789]]
Added Array:
 [[0.71624417 0.02706898 2.73139734 4.76696351 5.00976644 3.30828617]
 [0.23286547 0.50342743 2.95372138 4.5578113  5.09746869 3.62167849]
 [0.86302262 0.15763228 2.99242952 4.08500107 5.09445791 3.63360789]]
Reshaped Array:
 [[0.71624417 0.02706898]
 [2.73139734 4.76696351]
 [5.00976644 3.30828617]
 [0.23286547 0.50342743]
 [2.95372138 4.5578113 ]
 [5.09746869 3.62167849]
 [0.86302262 0.15763228]
 [2.99242952 4.08500107]
 [5.09445791 3.63360789]]
Transposed Array:
 [[0.71624417 2.73139734 5.00976644 0.23286547 2.95372138 5.09746869
  0.86302262 2.99242952 5.09445791]
 [0.02706898 4.76696351 3.30828617 0.50342743 4.5578113  3.62167849
  0.15763228 4.08500107 3.63360789]]
Mean Value: 2.79738059191759
Locations where all elements are greater than the mean:

In [86]:
# Assignment 2
'''
Create an array of length 20 that models a poisson distribution and center it around the mean and normalise it by dividing it by the standard deviation
(Centering around some value "a" is subtracting "a" from each element and normalising is to divide it by some factor)
'''
import numpy as np
#Create an array of length 20 with Poisson distribution
poisson_arr=np.random.poisson(lam=10,size=20)
print("Poisson Array:\n",poisson_arr)
#Compute mean and standard deviation
mean_val=np.mean(poisson_arr)
std_val=np.std(poisson_arr)
print("Mean Value:",mean_val)
print("Standard Deviation:",std_val)
#Center the array around the mean
centered_arr=poisson_arr-mean_val
print("Centered Array:\n",centered_arr)
#Normalize the array
normalized_arr=centered_arr/std_val
print("Normalized Array:\n",normalized_arr)




Poisson Array:
 [11  8 16  9 15 16  9  8 11  9 16  8 17  8 13  6 14  9 16 13]
Mean Value: 11.6
Standard Deviation: 3.455430508634199
Centered Array:
 [-0.6 -3.6  4.4 -2.6  3.4  4.4 -2.6 -3.6 -0.6 -2.6  4.4 -3.6  5.4 -3.6
  1.4 -5.6  2.4 -2.6  4.4  1.4]
Normalized Array:
 [-0.17363972 -1.04183834  1.27335798 -0.7524388   0.98395844  1.27335798
 -0.7524388  -1.04183834 -0.17363972 -0.7524388   1.27335798 -1.04183834
  1.56275752 -1.04183834  0.40515936 -1.62063742  0.6945589  -0.7524388
  1.27335798  0.40515936]
